export interface WikiField { name: string; meaning: string; example: string; use: string; mistake: string }
// Cada exemplo corresponde a um campo visível no formulário ou no resultado.
export const WIKI_FIELDS: WikiField[] = [
  { name: 'Base URL', meaning: 'Endereço principal de uma API. Aqui serve para montar a requisição de exemplo.', example: 'https://api.exemplo.dev', use: 'Preencha com o endereço inicial da API que está estudando.', mistake: 'Esquecer https:// ou colocar ?page=1 aqui.' },
  { name: 'Recurso / endpoint', meaning: 'Parte do endereço que identifica uma coleção.', example: 'alunos', use: 'Escreva alunos para usar os registros fictícios prontos.', mistake: 'Colocar a URL inteira ou uma barra no meio do nome.' },
  { name: 'ID', meaning: 'Número que identifica um registro específico.', example: '42', use: 'Preencha para buscar um aluno ou para PUT, PATCH e DELETE.', mistake: 'Usar um ID inexistente e esperar encontrar um registro.' },
  { name: 'Método HTTP', meaning: 'Verbo que descreve o que deseja fazer.', example: 'GET para consultar; POST para criar', use: 'Escolha o método antes de preencher o corpo.', mistake: 'Usar GET para criar um registro.' },
  { name: 'Query params', meaning: 'Filtros adicionados ao fim da URL após o sinal de interrogação.', example: 'chave status e valor ativo → ?status=ativo', use: 'Use para filtrar ou paginar uma lista com GET.', mistake: 'Colocar status=ativo inteiro na chave.' },
  { name: 'Header customizado', meaning: 'Informação adicional enviada junto com a requisição.', example: 'chave X-API-Key; valor chave-teste', use: 'Use quando a documentação da API pedir um cabeçalho próprio.', mistake: 'Escrever dois pontos depois do nome ou deixar o valor vazio.' },
  { name: 'Token Bearer', meaning: 'Credencial de acesso enviada no cabeçalho Authorization.', example: 'token-teste (fictício)', use: 'Use somente um valor inventado nesta simulação.', mistake: 'Colar uma credencial real em um site de estudo.' },
  { name: 'Body JSON', meaning: 'Dados enviados no corpo da requisição.', example: '{"nome":"Maria","curso":"ADS"}', use: 'Preencha para POST, PUT ou PATCH.', mistake: 'Esquecer aspas duplas nas chaves e nos textos.' },
  { name: 'Status code', meaning: 'Número que resume o resultado.', example: '200 sucesso; 201 criado; 404 não encontrado', use: 'Veja o código depois de simular para entender o resultado.', mistake: 'Achar que todos os códigos 2xx trazem um corpo.' },
  { name: 'Response body', meaning: 'Dados devolvidos pela simulação.', example: '{"id":42,"nome":"Maria"}', use: 'Leia a resposta para conferir o registro criado ou consultado.', mistake: 'Esperar um body no método HEAD ou na resposta 204.' },
  { name: 'cURL', meaning: 'Comando de terminal que representa a requisição montada.', example: "curl -X GET 'https://api.exemplo.dev/alunos'", use: 'Selecione o formato cURL para estudar os argumentos.', mistake: 'Executar o exemplo achando que a URL fictícia existe.' },
  { name: 'fetch', meaning: 'Função JavaScript que pode realizar requisições HTTP.', example: "fetch('https://api.exemplo.dev/alunos')", use: 'Selecione o formato fetch para ver um modelo de código.', mistake: 'Achar que mostrar o código executa uma chamada real.' },
  { name: 'JSON', meaning: 'Formato de texto para organizar dados em pares chave e valor.', example: '{"nome":"Maria"}', use: 'Use para representar os dados enviados e recebidos.', mistake: "Usar aspas simples em vez de aspas duplas." },
  { name: 'CRUD', meaning: 'Criar, consultar, atualizar e remover dados.', example: 'POST, GET, PUT/PATCH e DELETE', use: 'Faça as quatro operações em ordem para estudar o ciclo de um registro.', mistake: 'Confundir PUT, que substitui, com PATCH, que altera parte.' },
  ...([['GET','Consulta dados.','GET /alunos'],['POST','Cria um registro.','POST /alunos'],['PUT','Substitui os campos de um registro.','PUT /alunos/42'],['PATCH','Altera parte dos campos.','PATCH /alunos/42'],['DELETE','Remove um registro.','DELETE /alunos/42'],['HEAD','Consulta somente cabeçalhos.','HEAD /alunos'],['OPTIONS','Consulta métodos permitidos.','OPTIONS /alunos']] as const).map(([name, meaning, example]) => ({ name, meaning, example, use: `Selecione ${name} no campo Método HTTP.`, mistake: 'Esquecer de conferir ID e body exigidos pelo exercício.' }))
];
